version: 0.0
os: linux

files:
  - source: /
    #destination: /opt/CodeDeployApp
    destination: #HOME/CodeDeployApp
permissions:
  #- object: /opt/CodeDeployApp/
  - object: #HOME/CodeDeployApp
    owner: ubuntu
    group: ubuntu
    mode: 777
hooks:
  AfterInstall:
    # location은 프로젝트의 root경로를 기준
    - location: deploy.sh
      timeout: 60
      runas: root
